In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
X = np.array([[1, 1.9], [2, 3.1], [3, 4], [4, 5.1], [5, 5.9]])
X

array([[1. , 1.9],
       [2. , 3.1],
       [3. , 4. ],
       [4. , 5.1],
       [5. , 5.9]])

In [3]:
X.T

array([[1. , 2. , 3. , 4. , 5. ],
       [1.9, 3.1, 4. , 5.1, 5.9]])

In [4]:
np.mean(X, axis=0)

array([3., 4.])

In [5]:
U=np.median(X, axis=0)
U #media

array([3., 4.])

In [6]:
R=np.std(X, axis=0)
R #desviacion estandar

array([1.41421356, 1.41703917])

In [7]:
R2=np.var(X, axis=0, ddof=1)
R2 #varianza

array([2.5 , 2.51])

In [8]:
S=np.cov(X,rowvar=0)
S #matriz de covarianza

array([[2.5 , 2.5 ],
       [2.5 , 2.51]])

In [9]:
from numpy.linalg import inv

In [10]:
Sinv = inv(S)
Sinv # inversa S^-1

array([[ 100.4, -100. ],
       [-100. ,  100. ]])

In [11]:
(X-U)

array([[-2. , -2.1],
       [-1. , -0.9],
       [ 0. ,  0. ],
       [ 1. ,  1.1],
       [ 2. ,  1.9]])